export const FETCH_USER_PAYMENT_LIST_REQUEST = "FETCH_USER_PAYMENT_REQUEST";
export const FETCH_USER_PAYMENT_LIST_SUCCESS = "FETCH_USER_PAYMENT_SUCCESS";
export const FETCH_USER_PAYMENT_LIST_FAILURE = "FETCH_USER_PAYMENT_FAILURE";
export const ADD_NEW_USER_PAYMENT = "ADD_NEW_USER_PAYMENT";
